[package]
name = "static_type_map"
description = "A type map that works over all types implementing `Any`"
version = "0.5.1"
authors = ["Maël Obréjan <mael.obrejan@protonmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/malobre/static_type_map"
categories = ["no-std", "data-structures"]
readme = "README.md"
keywords = ["anymap", "typemap", "map"]
include = ["src/**/*", "Cargo.toml", "LICENSE"]

[dependencies]
hashbrown = { version = "0.12.0", optional = true }

[features]
default = ["send", "sync"]
send = []
sync = []
