[package]
name = "erased_set"
description = "A set of erased types"
version = "0.5.1"
authors = ["Maël Obréjan <mael.obrejan@protonmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/malobre/erased_set"
categories = ["no-std", "data-structures"]
readme = "README.md"
keywords = ["anymap", "typemap", "map", "set"]
include = ["src/**/*", "Cargo.toml", "LICENSE"]

[dependencies]
hashbrown = { version = "0.12.0", optional = true }

[features]
default = ["send", "sync"]
send = []
sync = []
