[package]
name = "static_type_map"
description = "A type map that works over all types implementing `Any`"
version = "0.1.2"
authors = ["Maël Obréjan <mael.obrejan@protonmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/malobre/static_type_map"
categories = ["no-std", "data-structures"]
readme = "README.md"
keywords = ["anymap", "typemap", "map"]
include = ["src/**/*", "Cargo.toml"]

[dependencies]
hashbrown = { version = "0.11", optional = true }

[features]
no_std = ["hashbrown"]
