name: Build, Test & Check Formatting

on:
  push:
    branch: master
  pull_request:
    branch: master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Check formatting
      run: cargo fmt -- --check
