name: Build, Test & Check Formatting

on:
  push:
    branch: master
  pull_request:
    branch: master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build without default features
      run: cargo build --no-default-features

    - name: Build with all features
      run: cargo build --all-features

    - name: Run tests without default features
      run: cargo test --no-default-features
      
    - name: Run tests with all features
      run: cargo test --all-features

    - name: Check formatting
      run: cargo fmt -- --check
