name: Rust Build, Test & Publish

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check if local version is different from published version
      run: local_version="$(cargo pkgid | cut -f2 -d'#')"; published_version="$(cargo pkgid static_type_map | cut -f2 -d'#')"; [ ! $local_version = $published_version ] && echo "::set_env name=CRATE_VERSION::$local_version"
    - name: Create a Release
      uses: actions/create-release@v1.1.1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ env.CRATE_VERSION }}
    - name: Publish crate
      run: cargo publish --token $TOKEN
      env:
        TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
