name: Publish

on:
  push:
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      crate_version: ${{ steps.check_version.outputs.crate_version}}

    steps:
    - uses: actions/checkout@v2

    - name: Build without default features
      run: cargo build --no-default-features

    - name: Build with all features
      run: cargo build --all-features

    - name: Run tests without default features
      run: cargo test --no-default-features
      
    - name: Run tests with all features
      run: cargo test --all-features

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Publish dry-run
      run: cargo publish --dry-run

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Publish crate
      run: cargo publish --token $TOKEN
      env:
        TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    - name: Fetch tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Create a Release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        release_name: ${{ steps.vars.outputs.tag }}
