name: Publish

on:
  push:
    branches: [ release ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get crate version
      run: |
        cargo generate-lockfile
        version="$(cargo pkgid | cut -f2 -d'#')"
        echo "::set-env name=CRATE_VERSION::$version"

    - name: Create a Release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ env.CRATE_VERSION }}

    - name: Publish crate
      run: cargo publish --token $TOKEN
      env:
        TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
